name:
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm i
      - run: webpack
  deploy:
    - uses: JamesIves/github-pages-deploy-action@12a916dfb718ab8fc2ec3ad7cb731a89d7d23332 # 4.1.5
      with:
        branch: gh-pages
        folder: dist
